# Exclude files based on a given pattern. Often used to exclude test files or fixtures
excluded_patterns:
  - "**/spec/**/*.rb"
  - "**/test/**/*.rb"
  - "**/vendor/**/*.rb"
  - "**/.bundle/**/*.rb"
  - "**/modules/**/*.rb"
  - "**/data/**/*.rb"
  - "**/db/**/*.rb"
  - "**/external/**/*.rb"
  - "**/plugins/**/*.rb"
  - "**/scripts/**/*.rb" # Some of this is old and may not need indexing???
  # - "**/lib/msf/core/post/android/priv.rb"

# Include files based on a given pattern. Can be used to index Ruby files that use different extensions
included_patterns:
  - "**/plugins/*.rb"
  - "**/lib/**/*.rb"
  - "**/bin/*"
  # - "**/*.rb"

# Exclude gems by name. If a gem is never referenced in the project's code and is only used as a tool, excluding it will
# speed up indexing and reduce the amount of results in features like definition or completion
excluded_gems:
  - rubocop
  - simplecov
  - redcarpet
  - yard
  - octokit
  - memory_profiler
  - ruby-prof
  - psych

# Include gems by name. Normally used to include development gems that are excluded by default
included_gems:
  - prism
  - rake
  